### ISSUE TITLE
API 명세서

### ISSUE THREAD

**Issue by SalguJam** [codestates-seb/seb45_pre_032#4]
API 명세서

**Comment by windeer9** [comment]
https://docs.google.com/spreadsheets/d/1HravVbrtSUWWsUEqflZqPVOrWYXriBd6nRkf4n9BjJs/edit#gid=2025321117

**Comment by SalguJam** [comment]
https://docs.google.com/spreadsheets/d/1HravVbrtSUWWsUEqflZqPVOrWYXriBd6nRkf4n9BjJs/edit#gid=1198337123
